"""SFZ generator for the sustain/staccato instruments.

Each per-note WAV is referenced by relative path so the resulting Samples/
folder + SFZ file can be moved as a unit.

Velocity layout (matches issue #1):

- Quiet group: vel 0-120, `xfout_lovel=100 xfout_hivel=120`, `seq_length=2`
- Loud group:  vel 100-127, `xfin_lovel=100 xfin_hivel=120`, `seq_length=1`

Sustain instrument also enables CC64 pedal behavior.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Region:
    sample_relpath: str
    midi: int
    velocity: str  # "quiet" or "loud"
    rr: int


@dataclass
class InstrumentSpec:
    name: str  # e.g. "BubbysPiano_Sustain"
    is_sustain: bool  # toggles CC64 behavior + release time
    regions: list[Region] = field(default_factory=list)
    ampeg_release_seconds: float = 1.2
    amp_veltrack_quiet: int = 100
    amp_veltrack_loud: int = 40  # mitigates v=111 dip pre-xfade
    xfade_lo: int = 100
    xfade_hi: int = 120
    velocity_split: int = 110  # boundary between quiet and loud


def _interpolate_key_ranges(midi_notes: list[int]) -> dict[int, tuple[int, int]]:
    """Given the set of MIDI notes we have samples for, decide each note's
    `lokey..hikey` so that any missing keys are filled by the nearest available
    sample (pitch-shifted by Kontakt/sfizz). For a complete A0..C8 set, each
    note covers exactly its own MIDI value.
    """
    midi_sorted = sorted(set(midi_notes))
    result: dict[int, tuple[int, int]] = {}
    for i, m in enumerate(midi_sorted):
        prev_m = midi_sorted[i - 1] if i > 0 else m
        next_m = midi_sorted[i + 1] if i + 1 < len(midi_sorted) else m
        lo = (prev_m + m) // 2 + 1 if i > 0 else m
        hi = (m + next_m) // 2 if i + 1 < len(midi_sorted) else m
        result[m] = (lo, hi)
    return result


def render_sfz(spec: InstrumentSpec) -> str:
    """Return the SFZ file contents as a string."""
    notes = sorted({r.midi for r in spec.regions})
    key_ranges = _interpolate_key_ranges(notes)

    lines: list[str] = []
    lines.append(f"// {spec.name}")
    lines.append("// Generated by piano-sampler. Hand-edits will be overwritten on regen.")
    lines.append("")

    # ---- Quiet group ----
    lines.append("<group>")
    lines.append("// Quiet layer — velocities 0..120 with xfade-out across 100..120")
    lines.append(f"ampeg_release={spec.ampeg_release_seconds}")
    lines.append(f"amp_veltrack={spec.amp_veltrack_quiet}")
    lines.append("lovel=0")
    lines.append("hivel=120")
    lines.append(f"xfout_lovel={spec.xfade_lo}")
    lines.append(f"xfout_hivel={spec.xfade_hi}")
    lines.append("seq_length=2")
    if spec.is_sustain:
        lines.append("sustain_sw=on")
        lines.append("sustain_cc=64")
    lines.append("")
    for r in spec.regions:
        if r.velocity != "quiet":
            continue
        lo, hi = key_ranges[r.midi]
        lines.append("<region>")
        lines.append(f"sample={r.sample_relpath}")
        lines.append(f"pitch_keycenter={r.midi}")
        lines.append(f"lokey={lo} hikey={hi}")
        lines.append(f"seq_position={r.rr}")
        lines.append("")

    # ---- Loud group ----
    lines.append("<group>")
    lines.append("// Loud layer — velocities 100..127 with xfade-in across 100..120")
    lines.append(f"ampeg_release={spec.ampeg_release_seconds}")
    lines.append(f"amp_veltrack={spec.amp_veltrack_loud}")
    lines.append("lovel=100")
    lines.append("hivel=127")
    lines.append(f"xfin_lovel={spec.xfade_lo}")
    lines.append(f"xfin_hivel={spec.xfade_hi}")
    lines.append("seq_length=1")
    if spec.is_sustain:
        lines.append("sustain_sw=on")
        lines.append("sustain_cc=64")
    lines.append("")
    for r in spec.regions:
        if r.velocity != "loud":
            continue
        lo, hi = key_ranges[r.midi]
        lines.append("<region>")
        lines.append(f"sample={r.sample_relpath}")
        lines.append(f"pitch_keycenter={r.midi}")
        lines.append(f"lokey={lo} hikey={hi}")
        lines.append(f"seq_position={r.rr}")
        lines.append("")

    return "\n".join(lines)


def write_sfz(path: Path, spec: InstrumentSpec) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_sfz(spec))
